version: "3.2"

services:
  api:
    build: ./images/api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: dev5
      POSTGRES_PASSWORD: test123 
      POSTGRES_DB: dev5
      POSTGRES_HOST: db
      PORT: 3000
    volumes:
      - ./images/api/src:/usr/app/src
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "citest"]

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev5
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: dev5
    volumes:
      - ./_backup:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
